### ISSUE TITLE
Long Forgotten Memories AQ Gate Quest Chain Bugged

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#145] opened 2017-10-22 12:51 UTC
Original report by: Dellboi5

For this quest you are to go to southern Silithus and click on a crystal in the sand near AQ, this completes the quest and continues onto the next one however the crystal is not there. I have searched various websites/forums and found co-ordinates of where it should be, screenshots of it, videos and have also asked people on the server who have completed the quest recently. So I am fairly sure I am in the correct spot, it's simply not there.

I have not found anyone who has completed the quest since the scourge invasion patch a few days ago, some people said they completed it last week though, so I assume the patch has broken it. Obviously this is on the Anathema realm.

**Comment by Francheskoo** [comment] 2017-10-23 06:45
404'ed for 6 weeks

**Comment by pregunta** [comment] 2017-10-23 16:48
The crystal is near the bottom of the gong ramp, but the problem is that after you click the object, the complete button doesn't do anything. I have tried dropping the quest and picking it back up, same effect.

**Comment by thepparker** [comment] 2017-11-16 02:37
Resolved in #540

**Closed** 2017-11-28 10:11 UTC
Labels: Fix Needs QA, Resolved
