### ISSUE TITLE
Mailbox Icon appears by minimap but mailbox is empty

### ISSUE THREAD

**Issue by Alucard600** [LightsHope/server#409] opened 2017-10-31 01:53 UTC
On one of my characters I tried relogging, deleting wdb, resetting the ui nothing has worked, disabling all addons buying something in the AH and nothing has worked. Help

**Comment by GuybrushGit** [comment] 2017-10-31 02:26
Related to https://github.com/LightsHope/server/issues/123 https://github.com/LightsHope/server/issues/391

**Comment by GuybrushGit** [comment] 2017-10-31 20:49
Dont know what causes it, maybe related to the expired mails that aren't removed due the query limit.

**Comment by Cabro** [comment] 2017-10-31 21:19
One thing that causes it is by simply moving away from mailbox after you opened all the mails without closing it. Minimap icon stays active.

**Comment by Timx0915** [comment] 2017-11-02 17:02
I was saving BG marks in my mailbox and had a full mailbox when they fixed the BG mark saving. Problem is my mailbox is still full and have been since that (i know multiple people that have the same problem). which means i cant receive any mail from other players nor can i remove the _invisible_ marks.

**Comment by berillis** [comment] 2017-11-03 08:56
I noticed the mail notice popping frequently when my other character on the same account had received unread mail.

**Closed** 2017-11-14 08:07 UTC
Labels: Fix Needs QA

**Comment by dogmax** [comment] 2017-11-16 08:45
steps to reproduce
1) Receive a mail with a C.O.D. item
2) Don't buy the item nor return it; Let it sit in the mailbox until the timer runs out.
2.1) For me the timer was 2 days
(I didn't buy the item because I was low on gold - don't know if that has anything to do with it.)
3) Be logged OUT while the timer runs out.
