### ISSUE TITLE
[Gizelton Caravan] quest in Desolace bugged and giving credit for completion

### ISSUE THREAD

**Issue by cupanoodle** [LightsHope/server#717] opened 2017-11-20 05:30 UTC
The quest was completed successfully twice and did not give credit for completing the quest. Not sure why it didn't give me the credit so the second time I [recorded the whole quest to show the issue](https://streamable.com/nkt5y).

**Comment by dimefox** [comment] 2017-12-06 09:20
The problem is Rigger should not have let you take the quest before the caravan paused and announcement was made. This part should be fixed.

In your video, the two alliance actually take and complete the quest. It is possible for you to complete now, but you must accept the quest at that time and no sooner.

**Closed** 2017-12-26 08:43 UTC
Labels: QA Confirmed
